### ISSUE TITLE
roadmapping

### ISSUE THREAD

**Issue by serapath** [wizardamigos/editor-workshop#1]
## `@todo`
* [ ] make sure workshop gets published into "global" skilltree
* [ ] [`editor-workshop#3` publish play-workshop module 1.0.0](https://github.com/wizardamigos/editor-workshop/issues/3)
* [ ] [`editor-workshop#2` add meta workshop (workshop-workshop)](https://github.com/wizardamigos/editor-workshop/issues/2)
* [ ] add switching between skilltree/workshop+editor/dashboard
* [ ] add gamification (codecombat?)
* [ ] add phases like in Mailchimp
    * (e.g. create solidity contract, create frontend, manage your deployed contracts...)
* [ ] add notes to the editor (to get feedback/review on the code, like medium or google docs)
    * [ ] enable comments/notes (like on Medium) - to get automated feedback/mentors/clients (in the editor, like compilation errors)
---
